//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Client
    {
        public int ID { get; set; }
        public string sName { get; set; }
        public string sPhone { get; set; }
        public string sContent { get; set; }
        public string sEmail { get; set; }
        public string sQQ { get; set; }
        public string sAddress { get; set; }
        public System.DateTime dInsertTime { get; set; }
    }
}
