//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Templet
    {
        public int ID { get; set; }
        public string sTempletName { get; set; }
        public string sTempletEnName { get; set; }
        public string sTempletContent { get; set; }
        public string sTempletUrl { get; set; }
        public System.DateTime dInsertTime { get; set; }
        public Nullable<bool> bIsCompile { get; set; }
    }
}
