
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TG_User
{

    public int ID { get; set; }

    public string sUserName { get; set; }

    public string sPassword { get; set; }

    public string sPhone { get; set; }

    public string sRealName { get; set; }

    public int iUserType { get; set; }

    public bool bIsSuper { get; set; }

}

}
