//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_WebSite
    {
        public int ID { get; set; }
        public string sSiteName { get; set; }
        public string sSiteDNS { get; set; }
        public string sEmail { get; set; }
        public string sMobile { get; set; }
        public string sFax { get; set; }
        public string sPhone { get; set; }
        public string sQQNum { get; set; }
        public string sAddress { get; set; }
        public string sKeyWord { get; set; }
        public string sDescription { get; set; }
        public string sCopyRight { get; set; }
        public string sFiling { get; set; }
        public bool IsNeedVerify { get; set; }
    }
}
